name: Pull Request testing

on:
  pull_request:
    branches:
     - main


jobs:
  APITesting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: API Testing
        run: |
         exit 1